### ISSUE TITLE
Pretending json-stable-stringify has an es6 default export causes errors compiling in Typescript

### ISSUE THREAD

**Issue by jasongrout** [vega/vega-lite#3855]
I am having problems compiling JupyterLab with vega-lite 2.5.1 because vega-lite is importing the json-stable-stringify library like this:

https://github.com/vega/vega-lite/blob/40bd312601dde2c2e23947196e5f55f59d10d04d/src/util.ts#L1

My error is: 

```
../../node_modules/vega-lite/build/src/util.d.ts:1:8 - error TS1192: Module '"[snip]/node_modules/@types/json-stable-stringify/index"' has no default export.

1 import stableStringify from 'json-stable-stringify';
         ~~~~~~~~~~~~~~~
```
I can suppress the error by setting `"allowSyntheticDefaultImports": true` in the tsconfig, but I think that's still probably not doing the right thing, given I'm not using Babel or something else that is converting that import to a default import for me. Reading https://github.com/Microsoft/TypeScript/pull/5577, it seems that vega-lite should be importing this as `import * as stableStringify from 'json-stable-stringify'` to make it compatible across different kinds of loaders, including loaders that don't magically make a default export when there isn't one.

Thoughts?

**Comment by domoritz** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/json-stable-stringify/index.d.ts does not have a default export and I followed the recommendation from @weswigham in https://github.com/Microsoft/TypeScript/issues/21535#issuecomment-394036392. I don't have strong opinions as long as it works with rollup and Typescript 2.9 as well as with the JSON imports in https://github.com/vega/vega-lite/pull/3839.

**Comment by weswigham** [comment]
If `vega-lite` reexports the module for use elsewhere, it should be using the `import stableStringify  = require('json-stable-stringify')` import form - or at least that's the policy we enforce on DT to ensure the declaration files will work with all `module` (and `esModuleInterop`) configurations.

**Comment by jasongrout** [comment]
@weswigham - do you mean we should use that form if we use *anything* from the module (i.e., if any part of that module ends up being exported, i.e., the module's types are a dependency rather than a dev dependency? Or should we use that form only if we reexport the entire json-stable-stringify module?

**Comment by weswigham** [comment]
Only if you reexport the entire module, otherwise it shouldn't matter.
